site_name: OSG School 2025
site_url: https://osg-htc.org/school-2025/
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png
  custom_dir: overrides
  icon:
    admonition:
      halt: material/hand-back-left
      pro-tip: material/brain

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.critic


extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGSchool
      name: OSG School on Twitter

nav:
  - Home:                           index.md
  - Schedule:                       schedule.md
  - Health Guidelines:              health.md
  - Logistics:
    - General information:          logistics/index.md
    - Hotel information:            logistics/hotel.md
    - Location and transportation:  logistics/location.md
    - Visa requirements:            logistics/visas.md
    - Travel planning:              logistics/travel-planning.md
    - Travel advice:                logistics/travel-advice.md
    - Health guidelines:            logistics/health.md
    - Meal information:             logistics/meals.md
    - Dining options:               logistics/dining.md
    - Madison Fun Day:              logistics/fun-day.md
    - Long-term OSPool access:      logistics/projects.md
  - Materials:
    - Overview:                     materials/index.md

#
# To list the materials for the day, run the following command on this file:
#   sed -i 's/# DAY?//g' mkdocs.yml
# where the '?' should be replaced with the day number (1, 2, 3, 4)
# (Friday's materials are grouped with Thursday's under DAY4)
#
# DAY1    - Intro to HTCondor:
# DAY1      - Intro Exercises 1 - Running and Viewing Simple Jobs:
# DAY1        - 1.1 - Log in and look around: materials/htcondor/part1-ex1-login.md
# DAY1        - 1.2 - Experiment with HTCondor commands: materials/htcondor/part1-ex2-commands.md
# DAY1        - 1.3 - Run jobs!:   materials/htcondor/part1-ex3-jobs.md
# DAY1        - 1.4 - Read and interpret log files: materials/htcondor/part1-ex4-logs.md
# DAY1        - 1.5 - Determine resource needs: materials/htcondor/part1-ex5-request.md
# DAY1        - 1.6 - Remove jobs from the queue: materials/htcondor/part1-ex6-remove.md
# DAY1      - Bonus Exercises - Job Attributes and Handling:
# DAY1        - Bonus Exercise 1.7 - Explore condor_q: materials/htcondor/part1-ex7-queue.md
# DAY1        - Bonus Exercise 1.8 - Explore condor_status: materials/htcondor/part1-ex8-status.md
# DAY1      - Intro Exercises 2 - Running Many HTC Jobs:
# DAY1        - 2.1 - Work with input and output files:  materials/htcondor/part2-ex1-files.md
# DAY1        - 2.2 - Use queue N, $(Cluster), and $(Process): materials/htcondor/part2-ex2-queue-n.md
# DAY1        - 2.3 - Use queue from with custom variables: materials/htcondor/part2-ex3-queue-from.md
# DAY1        - Bonus Exercise 2.4 - Use queue matching with a custom variable: materials/htcondor/part2-ex4-queue-matching.md
# DAY2    - OSG:
# DAY2      - 1.1 - Log in to the OSPool Access Point: materials/osg/part1-ex1-login-scp.md
# DAY2      - 1.2 - Running jobs in the OSPool: materials/osg/part1-ex2-submit-osg.md
# DAY2      - 1.3 - Hardware differences between PATh and OSG: materials/osg/part1-ex3-hardware-diffs.md
# DAY2      - 1.4 - Software differences in OSPool: materials/osg/part1-ex4-software-diffs.md
# DAY2    - Troubleshooting Exercises:
# DAY2      - 1.1 - Troubleshooting Jobs: materials/troubleshooting/part1-ex1-troubleshooting.md
# DAY2      - 1.2 - Job Retry: materials/troubleshooting/part1-ex2-job-retry.md
# DAY2    - Software Exercises:
# DAY2      - Software Exercises 1 - Exploring Containers:
# DAY2        - 1.1 - Run and Explore Apptainer Containers: materials/software/part1-ex1-run-apptainer.md
# DAY2        - 1.2 - Use Apptainer Containers in OSPool Jobs: materials/software/part1-ex2-apptainer-jobs.md
# DAY2        - 1.3 - Use Docker Containers in OSPool Jobs: materials/software/part1-ex3-docker-jobs.md
# DAY2        - 1.4 - Build, Test, and Deploy an Apptainer Container: materials/software/part1-ex4-apptainer-build.md
# DAY2        - 1.5 - Choose Software Options: materials/software/part1-ex5-pick-an-option.md
# DAY2      - Software Exercises 2 - Preparing Scripts:
# DAY2        - 2.1 - Build an HTC-Friendly Executable: materials/software/part2-ex1-build-executable.md
# DAY2      - Software Exercises 3 -  Container Examples (Optional):
# DAY2        - 3.1 - Create an Apptainer Definition Files: materials/software/part3-ex1-apptainer-recipes.md
# DAY2        - 3.2 - Build Your Own Docker Container: materials/software/part3-ex2-docker-build.md
# DAY2      - Software Exercises 4 - Exploring Compiled Software (Optional):
# DAY2        - 4.1 - Download and Use Compiled Software: materials/software/part4-ex1-download.md
# DAY2        - 4.2 - Use a Wrapper Script To Run Software: materials/software/part4-ex2-wrapper.md
# DAY2        - 4.3 - Using Arguments With Wrapper Scripts: materials/software/part4-ex3-arguments.md
# DAY2      - Software Exercises 5 - Compiled Software Examples (Optional):
# DAY2        - 5.1 - Compiling a Research Software: materials/software/part5-ex1-prepackaged.md
# DAY2        - 5.2 - Compiling Python and Running Jobs: materials/software/part5-ex2-python.md
# DAY2        - 5.3 - Using Conda Environments: materials/software/part5-ex3-conda.md
# DAY2        - 5.4 - Compiling and Running a Simple Code: materials/software/part5-ex4-compiling.md
# DAY3    - Data Exercises:
# DAY3      - Data Exercises 1 - HTCondor File Transfer:
# DAY3        - 1.1 - Understanding a job's data needs: materials/data/part1-ex1-data-needs.md
# DAY3        - 1.2 - transfer_input_files, transfer_output_files, and remaps: materials/data/part1-ex2-file-transfer.md
# DAY3        - 1.3- Splitting input: materials/data/part1-ex3-blast-split.md
# DAY3      - Data Exercises 2 - Using OSDF:
# DAY3        - 2.1 - OSDF for inputs: materials/data/part2-ex1-osdf-inputs.md
# DAY3        - 2.2 - OSDF for outputs: materials/data/part2-ex2-osdf-outputs.md
# DAY4    - Scaling Up:
# DAY4      - Scaling Up - Organizing and Testing:
# DAY4        - 1.1 - Organizing HTC workloads: materials/scaling/part1-ex1-organization.md
# DAY4        - 1.2 - Composing Your Jobs: materials/scaling/part2-ex1-composing-the-job.md
# DAY4      - Exploring Resources:
# DAY4        - 2.1 - Log Into a Local Pool: materials/scaling/part2-ex1-chtc-node.md
# DAY4        - 2.2 - Hardware Differences Between OSPool and the CHTC Pool: materials/scaling/part2-ex2-hardware-diffs.md
# DAY4        - 2.3 - Software Differences Between OSPool and the CHTC Pool: materials/scaling/part2-ex3-software-diffs.md
# DAY4      - Exploring Jobs:
# DAY4        - 3.1 - Investigating Job Attributes: materials/scaling/part3-ex1-job-attributes.md
# DAY4        - 3.2 - Getting Job Information from Log Files: materials/scaling/part3-ex2-log-files.md
# DAY4    - DAGMan Exercises:
# DAY4      - 1.1 - A simple DAG: materials/workflows/part1-ex1-simple-dag.md
# DAY4      - 1.2 - A brief detour through the Mandelbrot set: materials/workflows/part1-ex2-mandelbrot.md
# DAY4      - 1.3 - A more complex DAG: materials/workflows/part1-ex3-complex-dag.md
# DAY4      - 1.4 - Handling jobs that fail with DAGMan: materials/workflows/part1-ex4-failed-dag.md
# DAY4      - 1.5  - Workflow Challenges: materials/workflows/part1-ex5-challenges.md
# DAY4    - Self-checkpointing:
# DAY4      - 1.1 - Trying out self-checkpointing: materials/checkpoint/part1-ex1-checkpointing.md
# DAY4    - Special Environments:
# DAY4      - 1.1 - GPUs: materials/special/part1-ex1-gpus.md
